### PR TITLE
Fix #23 by explicitly specifying npm package include files

### LINKED ISSUE #23: npm package cannot be used with Babel 6
I recently upgraded to Babel 6 and noticed the following issues w/ your npm package:

```
/project/node_modules/redux-immutablejs/lib/index.js: Unknown option: /project/node_modules/redux-immutablejs/.babelrc.stage
```

It's generally considered bad practice to publish .babelrc as part of your npm packages. Instead, you should be using the `files` attribute in your package.json (https://docs.npmjs.com/files/package.json#files).

Alternatively, you can upgrade your package to Babel 6.

### PR DESCRIPTION
**Pull request by natorojr**
Fixes #23

### CODE REVIEW

**Comment by natorojr** [comment]
Note, will require you to republish npm module.

Thanks

**Comment by astuetz** [comment]
+1, just planned to create the same PR

**Comment by pjcabrera** [comment]
+1, applying workaround described in #23 works for me

**Comment by asaf** [comment]
Thanks! just released 0.0.8 with this PR.

**Pull request merged**
